#!/usr/bin/env python3
"""
Packman — Pyqttyai build dispatcher.

Usage:
    python packman.py <profile> [--no-build] [--no-clean]

─────────────────────────────────────────────────────────────
Feature flags per profile
─────────────────────────────────────────────────────────────
n Profile Key            FWhisper OV-GenAI Cloud  OV-Optimum   Size
0  do-not-tell-me         ❌       ❌      ❌     ❌         ~60 MB
1  fwhisper               ✅       ❌      ❌     ❌         ~145 MB
2  ovgenai                ❌       ✅      ❌     ❌         ~170 MB
3  cloud                  ❌       ❌      ✅     ❌         ~93 MB
4  fwhisper-ovgenai       ✅       ✅      ❌     ❌         ~219 MB
5  fwhisper-cloud         ✅       ❌      ✅     ❌         ~151 MB
6  fwhisper-ovgenai-cloud ✅       ✅      ✅     ❌         ~227 MB
7  ovgenai-cloud          ❌       ✅      ✅     ❌         ~177 MB
8  ovfull-cloud           ❌       ✅      ✅     ✅         ~3 GB
9  fwhisper-ovfull-cloud  ✅       ✅      ✅     ✅         ~3.2 GB
10 full                   ✅       ✅      ✅     ✅+extras  ~3.3 GB
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import os
from pathlib import Path

# ─────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────
SPEC_DIR     = Path(__file__).resolve().parent
PROJECT_ROOT = SPEC_DIR.parent
GEN_DIR      = SPEC_DIR / "generated"
GEN_DIR.mkdir(exist_ok=True)

# ─────────────────────────────────────────────────────────────
# Feature flags per profile
# ─────────────────────────────────────────────────────────────
T = True
F = False
PROFILES: dict[tuple[str, str], dict[str, bool]] = {
    ('0',  "do-not-tell-me"):         {"fwhisper": F, "ovgenai": F, "cloud": F, "ovoptimum": F, "extras": F},
    ('1',  "fwhisper"):               {"fwhisper": T, "ovgenai": F, "cloud": F, "ovoptimum": F, "extras": F},
    ('2',  "ovgenai"):                {"fwhisper": F, "ovgenai": T, "cloud": F, "ovoptimum": F, "extras": F},
    ('3',  "cloud"):                  {"fwhisper": F, "ovgenai": F, "cloud": T, "ovoptimum": F, "extras": F},
    ('4',  "fwhisper-ovgenai"):       {"fwhisper": T, "ovgenai": T, "cloud": F, "ovoptimum": F, "extras": F},
    ('5',  "fwhisper-cloud"):         {"fwhisper": T, "ovgenai": F, "cloud": T, "ovoptimum": F, "extras": F},
    ('6',  "fwhisper-ovgenai-cloud"): {"fwhisper": T, "ovgenai": T, "cloud": T, "ovoptimum": F, "extras": F},
    ('7',  "ovgenai-cloud"):          {"fwhisper": F, "ovgenai": T, "cloud": T, "ovoptimum": F, "extras": F},
    ('8',  "cloud-ovfull"):           {"fwhisper": F, "ovgenai": T, "cloud": T, "ovoptimum": T, "extras": F},
    ('9',  "fwhisper-cloud-ovfull"):  {"fwhisper": T, "ovgenai": T, "cloud": T, "ovoptimum": T, "extras": F},
    ('10', "full"):                   {"fwhisper": T, "ovgenai": T, "cloud": T, "ovoptimum": T, "extras": T},
}

# ─────────────────────────────────────────────────────────────
# Spec template
# ─────────────────────────────────────────────────────────────
SPEC_TEMPLATE = '''# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by packman.py — profile: {profile}
from pathlib import Path
from PyInstaller.utils.hooks import collect_data_files, collect_all

SPEC_DIR     = Path(SPECPATH).resolve()
PROJECT_ROOT = SPEC_DIR.parent.parent  # generated/ -> packing/ -> root

block_cipher = None

datas        = [(str(PROJECT_ROOT / 'images'), 'images')]
binaries     = []
hiddenimports = []

def _merge(pkg):
    d, b, h = collect_all(pkg)
    datas.extend(d); binaries.extend(b); hiddenimports.extend(h)

# ── 🛡️ Silero VAD — bundled in ALL profiles except do-not-tell-me ──
# Tiny (1.2 MB) ONNX model — eliminates Whisper hallucinations on silence/noise.
# Standalone wrapper means it works with cloud-only AND OV-only profiles.
if any([{fwhisper}, {cloud}, {ovgenai}, {ovoptimum}, {extras}]):
    datas.append((
        str(PROJECT_ROOT / "pyqttyai" / "audio" / "assets" / "silero_vad.onnx"),
        "pyqttyai/audio/assets",
    ))
    # 🧮 onnxruntime is needed for inference (cloud-only profiles too)
    _merge("onnxruntime")
    hiddenimports.append("onnxruntime")

# ── Faster-Whisper stack ───────────────────────────────────────────
if {fwhisper}:
    datas.extend(collect_data_files('faster_whisper'))
    _merge('faster_whisper')
    _merge('ctranslate2')
    _merge('tokenizers')
    _merge('huggingface_hub')

# ── Cloud stack (Groq + OpenAI-compat) ──────────────────────
if {cloud}:
    _merge('groq')
    _merge('openai')
    hiddenimports += ['httpx', 'httpcore', 'h11', 'anyio', 'sniffio', 'distro']

# ── OpenVINO-GenAI (lean runtime ~200 MB) ───────────────────
if {ovgenai}:
    _merge('openvino')
    _merge('openvino_genai')
    _merge('openvino_tokenizers')
    _merge('huggingface_hub')

# ── OpenVINO-Optimum (heavy: torch + transformers ~3 GB) ────
if {ovoptimum}:
    _merge('optimum')
    _merge('optimum.intel')
    _merge('transformers')
    _merge('torch')
    _merge('huggingface_hub')
    _merge('safetensors')
    # nncf is often needed for quantization
    try:
        _merge('nncf')
    except Exception:
        pass

# ── Extras (full profile only) ──────────────────────────────
if {extras}:
    _merge('sentencepiece')
    _merge('accelerate')
    _merge('datasets')

excludes=[
    'tkinter', 'matplotlib', 'pytest', 'IPython', 'notebook', 'jupyter',
    # 🪶 OV-GenAI no longer needs these
    'librosa', 'numba', 'llvmlite', 'soxr', 'audioread', 'pooch',
    'samplerate', 'resampy',
]
if not {fwhisper}:
    excludes += ['ctranslate2', 'faster_whisper', 'tokenizers']
if not {ovoptimum}:
    excludes += ['torch', 'transformers', 'optimum', 'accelerate']
if not any([{fwhisper}, {cloud}, {ovgenai}, {ovoptimum}, {extras}]):
    excludes.extend(['numpy', 'onnxruntime'])

a = Analysis(
    [str(PROJECT_ROOT / 'main.py')],
    pathex=[str(PROJECT_ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=list(set(hiddenimports)),
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[str(PROJECT_ROOT / 'packing' / 'pyqttyai_runtime_hook.py')],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Pyqttyai_{profile}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[
        'vcruntime140.dll', 'python3*.dll',
        'onnxruntime*.dll', 'onnxruntime_providers_*.dll',
        'openvino*.dll', 'torch*.dll',
    ],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(PROJECT_ROOT / 'images' / 'pyqttyai.ico'),
)
'''

# ─────────────────────────────────────────────────────────────
# Core
# ─────────────────────────────────────────────────────────────
def render_spec(profile: tuple[str, str]) -> Path:
    flags = PROFILES[profile]
    spec_text = SPEC_TEMPLATE.format(
        profile=profile[1],
        fwhisper=flags["fwhisper"],
        cloud=flags["cloud"],
        ovgenai=flags["ovgenai"],
        ovoptimum=flags["ovoptimum"],
        extras=flags["extras"],
    )
    spec_path = GEN_DIR / f"Pyqttyai_{profile[1]}.spec"
    spec_path.write_text(spec_text, encoding="utf-8")
    return spec_path


def run_pyinstaller(spec_path: Path, clean: bool) -> int:
    cmd = [sys.executable, "-m", "PyInstaller", str(spec_path), "--noconfirm"]
    if clean:
        cmd.append("--clean")
    print(f"\n🚀 Running: {' '.join(cmd)}\n")
    return subprocess.call(cmd, cwd=PROJECT_ROOT)


# ─────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────
def main() -> int:
    print(__doc__)
    profile_choices = ' '.join(f"{p[0]} {p[1]}" for p in PROFILES).split()
    parser = argparse.ArgumentParser(description="Pyqttyai build dispatcher")
    parser.add_argument("profile", choices=profile_choices, help="Profile number or name")
    parser.add_argument("--no-build", action="store_true", help="Only generate the .spec")
    parser.add_argument("--no-clean", action="store_true", help="Skip --clean")
    args = parser.parse_args()

    profile = list(filter(lambda x: args.profile in x, PROFILES.keys()))[0]

    print(f"📦 Profile: {profile}")
    print(f"   Flags : {PROFILES[profile]}")

    spec = render_spec(profile)
    print(f"📝 Spec generated: {spec.relative_to(PROJECT_ROOT)}")

    if args.no_build:
        print("⏭️  Skipping build (--no-build).")
        return 0

    rc = run_pyinstaller(spec, clean=not args.no_clean)
    if rc == 0:
        ext = ".exe" if os.name == "nt" else ""
        exe = PROJECT_ROOT / "dist" / f"Pyqttyai_{profile[1]}{ext}"
        print(f"\n✅ Done! → {exe}")
    else:
        print(f"\n❌ PyInstaller exited with code {rc}")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
